/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsAuctionIdRouteImport } from './routes/auctions.$auctionId'
import { Route as AuthenticatedMyAuctionsIndexRouteImport } from './routes/_authenticated/my-auctions.index'
import { Route as AuthenticatedMyAuctionsAuctionIdRouteImport } from './routes/_authenticated/my-auctions.$auctionId'
import { Route as AuthenticatedMyAuctionsNewRouteImport } from './routes/_authenticated/my-auctions.new'
import { Route as AuthenticatedMyProductsIndexRouteImport } from './routes/_authenticated/my-products.index'
import { Route as AuthenticatedMyProductsProductIdRouteImport } from './routes/_authenticated/my-products.$productId'
import { Route as AuthenticatedMyProductsNewRouteImport } from './routes/_authenticated/my-products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdRoute = AuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyAuctionsIndexRoute =
  AuthenticatedMyAuctionsIndexRouteImport.update({
    id: '/my-auctions/',
    path: '/my-auctions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsAuctionIdRoute =
  AuthenticatedMyAuctionsAuctionIdRouteImport.update({
    id: '/my-auctions/$auctionId',
    path: '/my-auctions/$auctionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsNewRoute =
  AuthenticatedMyAuctionsNewRouteImport.update({
    id: '/my-auctions/new',
    path: '/my-auctions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyProductsIndexRoute =
  AuthenticatedMyProductsIndexRouteImport.update({
    id: '/my-products/',
    path: '/my-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyProductsProductIdRoute =
  AuthenticatedMyProductsProductIdRouteImport.update({
    id: '/my-products/$productId',
    path: '/my-products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyProductsNewRoute =
  AuthenticatedMyProductsNewRouteImport.update({
    id: '/my-products/new',
    path: '/my-products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/my-auctions/$auctionId': typeof AuthenticatedMyAuctionsAuctionIdRoute
  '/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/my-products/$productId': typeof AuthenticatedMyProductsProductIdRoute
  '/my-products/new': typeof AuthenticatedMyProductsNewRoute
  '/my-auctions/': typeof AuthenticatedMyAuctionsIndexRoute
  '/my-products/': typeof AuthenticatedMyProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions': typeof AuctionsIndexRoute
  '/my-auctions/$auctionId': typeof AuthenticatedMyAuctionsAuctionIdRoute
  '/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/my-products/$productId': typeof AuthenticatedMyProductsProductIdRoute
  '/my-products/new': typeof AuthenticatedMyProductsNewRoute
  '/my-auctions': typeof AuthenticatedMyAuctionsIndexRoute
  '/my-products': typeof AuthenticatedMyProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/_authenticated/my-auctions/$auctionId': typeof AuthenticatedMyAuctionsAuctionIdRoute
  '/_authenticated/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/_authenticated/my-products/$productId': typeof AuthenticatedMyProductsProductIdRoute
  '/_authenticated/my-products/new': typeof AuthenticatedMyProductsNewRoute
  '/_authenticated/my-auctions/': typeof AuthenticatedMyAuctionsIndexRoute
  '/_authenticated/my-products/': typeof AuthenticatedMyProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/forgot-password'
    | '/how-it-works'
    | '/reset-password'
    | '/sell'
    | '/account'
    | '/admin'
    | '/profile'
    | '/auctions/$auctionId'
    | '/auctions/'
    | '/my-auctions/$auctionId'
    | '/my-auctions/new'
    | '/my-products/$productId'
    | '/my-products/new'
    | '/my-auctions/'
    | '/my-products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/forgot-password'
    | '/how-it-works'
    | '/reset-password'
    | '/sell'
    | '/account'
    | '/admin'
    | '/profile'
    | '/auctions/$auctionId'
    | '/auctions'
    | '/my-auctions/$auctionId'
    | '/my-auctions/new'
    | '/my-products/$productId'
    | '/my-products/new'
    | '/my-auctions'
    | '/my-products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/categories'
    | '/forgot-password'
    | '/how-it-works'
    | '/reset-password'
    | '/sell'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/auctions/$auctionId'
    | '/auctions/'
    | '/_authenticated/my-auctions/$auctionId'
    | '/_authenticated/my-auctions/new'
    | '/_authenticated/my-products/$productId'
    | '/_authenticated/my-products/new'
    | '/_authenticated/my-auctions/'
    | '/_authenticated/my-products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  AuctionsAuctionIdRoute: typeof AuctionsAuctionIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId': {
      id: '/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof AuctionsAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-auctions/': {
      id: '/_authenticated/my-auctions/'
      path: '/my-auctions'
      fullPath: '/my-auctions/'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/$auctionId': {
      id: '/_authenticated/my-auctions/$auctionId'
      path: '/my-auctions/$auctionId'
      fullPath: '/my-auctions/$auctionId'
      preLoaderRoute: typeof AuthenticatedMyAuctionsAuctionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/new': {
      id: '/_authenticated/my-auctions/new'
      path: '/my-auctions/new'
      fullPath: '/my-auctions/new'
      preLoaderRoute: typeof AuthenticatedMyAuctionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products/': {
      id: '/_authenticated/my-products/'
      path: '/my-products'
      fullPath: '/my-products/'
      preLoaderRoute: typeof AuthenticatedMyProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products/$productId': {
      id: '/_authenticated/my-products/$productId'
      path: '/my-products/$productId'
      fullPath: '/my-products/$productId'
      preLoaderRoute: typeof AuthenticatedMyProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products/new': {
      id: '/_authenticated/my-products/new'
      path: '/my-products/new'
      fullPath: '/my-products/new'
      preLoaderRoute: typeof AuthenticatedMyProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMyAuctionsAuctionIdRoute: typeof AuthenticatedMyAuctionsAuctionIdRoute
  AuthenticatedMyAuctionsNewRoute: typeof AuthenticatedMyAuctionsNewRoute
  AuthenticatedMyProductsProductIdRoute: typeof AuthenticatedMyProductsProductIdRoute
  AuthenticatedMyProductsNewRoute: typeof AuthenticatedMyProductsNewRoute
  AuthenticatedMyAuctionsIndexRoute: typeof AuthenticatedMyAuctionsIndexRoute
  AuthenticatedMyProductsIndexRoute: typeof AuthenticatedMyProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMyAuctionsAuctionIdRoute: AuthenticatedMyAuctionsAuctionIdRoute,
  AuthenticatedMyAuctionsNewRoute: AuthenticatedMyAuctionsNewRoute,
  AuthenticatedMyProductsProductIdRoute: AuthenticatedMyProductsProductIdRoute,
  AuthenticatedMyProductsNewRoute: AuthenticatedMyProductsNewRoute,
  AuthenticatedMyAuctionsIndexRoute: AuthenticatedMyAuctionsIndexRoute,
  AuthenticatedMyProductsIndexRoute: AuthenticatedMyProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  AuctionsAuctionIdRoute: AuctionsAuctionIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
